name: Run Notebooks

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install package
              run: poetry install -E "en-core-web-md sc-toolbox"

            - uses: asegal/run-notebook@v1
              env:
                  RUNNER: ${{ toJson(runner) }}
                  SECRETS: ${{ toJson(secrets) }}
                  GITHUB: ${{ toJson(github) }}
              with:
                  notebook: "notebooks/mimic_2.ipynb"
                  # params: "notebooks/ci_params.json"
                  isReport: False
            - uses: actions/upload-artifact@master
              if: always()
              with:
                  name: output
                  path: ${{ RUNNER.temp }}/nb-runner
              env:
                  RUNNER: ${{ toJson(runner) }}
