name: Run Notebooks

on: [push]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install package
              run: poetry install -E "en-core-web-md sc-toolbox"

            - name: Install nbconvert
              run: pip install nbconvert

            - name: Run MIMIC-II Notebook
              run:  jupyter nbconvert --to notebook --execute notebooks/mimic_2.ipynb


